Weighted pMDS - Feature/exe-1782
PixelgenTechnologies/pixelator pull request #149
Opened 2024-06-11 12:59 UTC by ludvigla

## Description

Adds additional arguments to `layout_pmds` to use edge weights and noise.

The new option `use_weights` accepts a numpy array with any non-negative edge weights with one element per edge. Alternatively, one can set it to 'prob_dist' which activates the use of edge weights computed from transition probabilities. The default is None, in which case no edge weights are used. 

### Brief explanation of edge weights

Weights are calculated for edges in the graph from the bidirectional transition probability of a random walker. For an undirected edge $e_{i,j}$, we define the bidirectional transition probability $P(e_{u,v})$ as the probability of transitioning from $u$ to $v$ and back to $u$ in $k$ steps. Note that it doesn't matter what node the random walker starts from since it has to go in both directions. In this computation, we also allow self-loops in the graph to slow the transition of the random walker.

Then, we assume that there is a relationship between the bidirectional transition probability and an exponential function which decays with distance:

$P(e_{u,v}) \propto e^{-d(u, v)}$

If the relationship holds, we can solve for $d(u, v)$ to estimate weights that should be proportional to distance: 

$w_{u,v} = -\log(P(e_{u,v}))$

Examples demonstrating this weighting scheme is available in `layout_with_weighted_pmds` in pixelatorR-internal. The strategy is entirely based on empirical observations but does seem to improve the variance explained when computing pMDS layouts substantially.

### Noise

By setting `add_noise=True`, additional noise is added to the layout coordinates. After the initial layout has been computed, we calculate the layout distances for each edge (distance between end nodes). From these distances, we calculate the standard deviation and use this value to sample offsets along all three axes (x, y, z) from a normal distribution. The effect is that we wiggle the node coordinates a little such that the risk of overlap is reduced. This is useful for pMDS where nodes can have identical layout coordinates.

Fixes: exe-1782

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce it when relevant.

## PR checklist:

- [x] This comment contains a description of changes (with reason).
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and documentation and corrected any misspellings
- [ ] I have documented any significant changes to the code in [CHANGELOG.md](../CHANGELOG.md)

2024-06-11 21:55 UTC, ambarrio commented
Check tests not passing.

2024-06-12 13:08 UTC, ptajvar approved these changes
Looks great to me!

2024-06-14 12:33 UTC, ludvigla commented
@ambarrio , now I have added wpmds_3d as the default option in `pmds_layout` and it should be possible to run it with the pre-compute layout cli option.

A few things to think about here:

- I have set the default number of pivot points in pMDS to 200 instead of 50. I think 50 might be a bit low for larger graphs. 
- It is possible that some graphs might have fewer than 200 pivot points and in that case the layout computation will fail. Maybe we should resort to using all available nodes as pivot points if the total number of nodes is lower than 200.

2024-06-14 12:41 UTC, ambarrio commented
I can review if it is ready to go.

1- good
2- ok, but I think we run layout as part of the nf-core/pixelator and we never come down to 200 nodes in annotated cells. But as a safeguard when it is run under an API call or from CLI in the unannotated PXL file, makes sense.

2024-06-14 13:07 UTC, ludvigla commented
For point 2, I'm just not sure where that check should be placed.

There are still some tests failing, and I cannot figure out why. There's a mismatch in the generated figures when running the 2d_plot tests. My suspicion is that it's related to the `setup_basic_pixel_dataset`.

2024-06-14 13:48 UTC, ambarrio commented
Probably just here: https://github.com/PixelgenTechnologies/pixelator/blob/482a2c7811de8a4ecc21cca521f9ce20dda3fbb0/src/pixelator/graph/backends/implementations/_networkx.py#L768

where we can write: `pivots = len(g.nodes)`

and then, it they become very few (i.e. <50), they will raise here: https://github.com/PixelgenTechnologies/pixelator/blob/482a2c7811de8a4ecc21cca521f9ce20dda3fbb0/src/pixelator/graph/backends/implementations/_networkx.py#L779

2024-06-14 14:54 UTC, ludvigla commented
Perhaps we should throw a warning if this happens?

2024-06-14 15:09 UTC, ambarrio requested changes
I sent these ones also we were talking in the live review....

And I will check the tests.

2024-06-17 07:20 UTC, ludvigla commented on src/pixelator/graph/backends/implementations/_networkx.py
> +    add_noise: bool = False,
This option has been removed!

2024-06-17 07:23 UTC, ludvigla commented on src/pixelator/graph/backends/implementations/_networkx.py
> +    # Add 1 to the diagonal
Added comment

2024-06-17 07:23 UTC, ludvigla commented on src/pixelator/graph/backends/implementations/_networkx.py
> +    P_step_bidirectional = P_step.multiply(P_step.T)
Added comment

2024-06-18 14:19 UTC, ambarrio reviewed
IS this resolving the test issues?

2024-06-18 14:24 UTC, ludvigla commented
No it doesn't, but it improves computational speed. I need to fix the tests tomorrow.

2024-06-23 20:37 UTC, ambarrio approved these changes
I approve. Great work!

One question only, when we run this as default option, will we run it with "prob_dist" as default as weighting strategy?

2024-06-24 07:54 UTC, ludvigla commented
> I approve. Great work!
> 
> One question only, when we run this as default option, will we run it with "prob_dist" as default as weighting strategy?

We have a test in place `test_generate_precomputed_layouts_for_components_with_all_components` to check that the default option is `wpmds_3d` which runs `pmds_layout` with `weights='prob_dist'`. I just quickly checked that the output makes sense with default settings, but I haven't actually tested the pipeline on real data. The default value when setting `--layout-algorithm` with the cli is `wpmds_3d` so it should be fine, but again, I haven't tested it on real data.

2024-06-24 08:34 UTC, ambarrio commented
Great! We will test this now. And it makes sense with all the internal data you have shown. I think you should go ahead and merge.

2024-06-24 08:44 UTC, merged